GET https://pizza-api.projectcodex.net/api/pizzas

### Create a cart
GET https://pizza-api.projectcodex.net/api/pizza-cart/create?username=motitswe-m

### Get a cart
GET https://pizza-api.projectcodex.net/api/pizza-cart/rwoNroZWXz/get

### Add a pizza to the cart
POST https://pizza-api.projectcodex.net/api/pizza-cart/add
Content-Type: application/json

{
    "cart_code": "rwoNroZWXz",
    "pizza_id": 3
}

### Add a pizza to the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/add
Content-Type: application/json

{
    "cart_code": "rwoNroZWXz",
    "pizza_id": 7
}

### Remove from the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/remove
Content-Type: application/json

{
    "cart_code": "rwoNroZWXz",
    "pizza_id": 10
}

### GET all the carts for a given user

GET https://pizza-api.projectcodex.net/api/pizza-cart/username/motitswe-m

### GET all the active carts for a user
GET https://pizza-api.projectcodex.net/api/pizza-cart/username/motitswe-m/active

### Pay for a pizza from the cart
POST https://pizza-api.projectcodex.net/api/pizza-cart/pay
Content-Type: application/json

{
    "cart_code": "rwoNroZWXz",
    "amount": 800
}

### Featured Items To Get
GET https://pizza-api.projectcodex.net/api/pizzas/featured?username=motitswe-m

##### Set a given pizza id to be featured - max 3 ids
POST https://pizza-api.projectcodex.net/api/pizzas/featured
Content-Type: application/json

{
    "username": "motitswe-m",
    "pizza_id": 4
}
